### ISSUE TITLE
iter_frames returns nothing if time period between start and end is too small (?)

### ISSUE THREAD

**Issue by aschle** [BioroboticsLab/bb_binary#17] opened 2017-01-14 19:47 UTC
When using `start` and `end` as arguments for `iter_frames`, and the time period is kind of small, then nothing is returned. I am not sure if it should behave like this (?), and its not an issue. But I thought maybe it is not intuitive. I guess `iter_fnames` is not returning anything, but should (?).

If I ask for 10 seconds of frames, I would assume getting about 30 frames for each camera, but thats not the case.

```
path = "../00_Data/testset_2015_20m/2015082215/"
repo = Repository(path)

min = sys.maxsize
for frame, fc in repo.iter_frames():
    if (frame.timestamp < min):
        min = frame.timestamp
print(min)
print(datetime.datetime.fromtimestamp(min))

s = min + 1
e = s + 60
print(datetime.datetime.fromtimestamp(s))
print(datetime.datetime.fromtimestamp(e))

count = 0
for frame, fc in repo.iter_frames(begin=s, end=e, cam=None):
    count += 1
print(count)
```

**Comment by b2m** [comment] 2017-01-15 10:14
This is a duplicate of #9.

**Closed** 2017-01-23 13:38 UTC
Labels: duplicate
